from constants import TYPE, COLOR, EXPANSION

expansion_cards = {
    EXPANSION.BASE: [{
        "name": "Ás",
        "type": TYPE.UNIT,
        "power": 2,
        "gold": 1,
        "unit": 'ace',
        "colors": [COLOR.YELLOW, COLOR.PURPLE, COLOR.GREEN, COLOR.BLUE],
        "count": 1,
    }, {
        "name": "Arqueira",
        "type": TYPE.UNIT,
        "power": 2,
        "gold": 2,
        "unit": 'archer',
        "colors": [COLOR.ORANGE, COLOR.GREEN],
        "count": 1,
    }, {
        "name": "Assassino",
        "type": TYPE.UNIT,
        "power": 1,
        "gold": 3,
        "unit": 'assassin',
        "colors": [COLOR.PURPLE, COLOR.RED],
        "count": 1,
    }, {
        "name": "Construtor",
        "type": TYPE.UNIT,
        "power": 1,
        "gold": 3,
        "unit": 'builder',
        "colors": [COLOR.PURPLE, COLOR.BLUE, COLOR.ORANGE, COLOR.RED, COLOR.YELLOW, COLOR.GREEN],
        "count": 1,
    }, {
        "name": "Dragão",
        "type": TYPE.UNIT,
        "power": 5,
        "gold": 2,
        "unit": 'dragon',
        "colors": [COLOR.RED, COLOR.ORANGE],
        "count": 1,
    }, {
        "name": "Fazendeiro",
        "type": TYPE.UNIT,
        "power": 1,
        "gold": 3,
        "unit": 'farmer',
        "colors": [COLOR.RED, COLOR.YELLOW, COLOR.GREEN, COLOR.PURPLE, COLOR.BLUE, COLOR.ORANGE],
        "count": 1,
    }, {
        "name": "Goblin",
        "type": TYPE.UNIT,
        "power": 2,
        "gold": 1,
        "unit": 'goblin',
        "colors": [COLOR.BLUE, COLOR.YELLOW, COLOR.RED],
        "count": 1,
    }, {
        "name": "Golem",
        "type": TYPE.UNIT,
        "power": 2,
        "gold": 2,
        "unit": 'golem',
        "colors": [COLOR.GREEN, COLOR.YELLOW],
        "count": 1,
    }, {
        "name": "Herói",
        "type": TYPE.UNIT,
        "power": 3,
        "gold": 2,
        "unit": 'hero',
        "colors": [COLOR.BLUE, COLOR.GREEN],
        "count": 1,
    }, {
        "name": "Coringa",
        "type": TYPE.UNIT,
        "power": 2,
        "gold": 1,
        "unit": 'joker',
        "colors": [COLOR.GREEN, COLOR.PURPLE],
        "count": 1,
    }, {
        "name": "Rei",
        "type": TYPE.UNIT,
        "power": 0,
        "gold": 0,
        "unit": 'king',
        "colors": [COLOR.GREEN, COLOR.YELLOW],
        "count": 1,
    }, {
        "name": "Cavaleiro",
        "type": TYPE.UNIT,
        "power": 2,
        "gold": 1,
        "unit": 'knight',
        "colors": [COLOR.YELLOW, COLOR.GREEN, COLOR.BLUE, COLOR.PURPLE],
        "count": 1,
    }, {
        "name": "Comerciante",
        "type": TYPE.UNIT,
        "power": 0,
        "gold": 3,
        "unit": 'merchant',
        "colors": [COLOR.ORANGE, COLOR.YELLOW],
        "count": 1,
    }, {
        "name": "Orc",
        "type": TYPE.UNIT,
        "power": 2,
        "gold": 2,
        "unit": 'orc',
        "colors": [COLOR.RED, COLOR.ORANGE],
        "count": 1,
    }, {
        "name": "Padre",
        "type": TYPE.UNIT,
        "power": 0,
        "gold": 0,
        "unit": 'priest',
        "colors": [COLOR.ORANGE, COLOR.RED],
        "count": 1,
    }, {
        "name": "Princesa",
        "type": TYPE.UNIT,
        "power": 0,
        "gold": 5,
        "unit": 'princess',
        "colors": [COLOR.GREEN, COLOR.BLUE, COLOR.YELLOW, COLOR.PURPLE],
        "count": 1,
    }, {
        "name": "Batedora",
        "type": TYPE.UNIT,
        "power": 1,
        "gold": 1,
        "unit": 'scout',
        "colors": [COLOR.RED, COLOR.PURPLE, COLOR.ORANGE],
        "count": 1,
    }, {
        "name": "Ladra",
        "type": TYPE.UNIT,
        "power": 1,
        "gold": 1,
        "unit": 'thief',
        "colors": [COLOR.YELLOW, COLOR.BLUE, COLOR.PURPLE],
        "count": 1,
    }, {
        "name": "Guerreiro",
        "type": TYPE.UNIT,
        "power": 2,
        "gold": 1,
        "unit": 'warrior',
        "colors": [COLOR.ORANGE, COLOR.BLUE, COLOR.RED],
        "count": 1,
    }, {
        "name": "Mago",
        "type": TYPE.UNIT,
        "power": 4,
        "gold": 2,
        "unit": 'wizard',
        "colors": [COLOR.RED, COLOR.PURPLE, COLOR.ORANGE, COLOR.BLUE],
        "count": 1,
    }, {
        "name": "Coelho",
        "type": TYPE.ANIMAL,
        "power": 0,
        "gold": 1,
        "unit": 'bunny',
        "colors": [COLOR.GRAY],
        "count": 2,
    }, {
        "name": "Galinha",
        "type": TYPE.ANIMAL,
        "power": 0,
        "gold": 1,
        "unit": 'chicken',
        "colors": [COLOR.GRAY],
        "count": 2,
    }, {
        "name": "Porco",
        "type": TYPE.ANIMAL,
        "power": 0,
        "gold": 1,
        "unit": 'pig',
        "colors": [COLOR.GRAY],
        "count": 2,
    }, {
        "name": "Ovelha",
        "type": TYPE.ANIMAL,
        "power": 0,
        "gold": 1,
        "unit": 'sheep',
        "colors": [COLOR.GRAY],
        "count": 1,
    }, {
        "name": "Castelo",
        "type": TYPE.BUILDING,
        "power": 0,
        "gold": 4,
        "unit": 'castle',
        "colors": [COLOR.GRAY],
        "count": 1,
    }, {
        "name": "Pousada",
        "type": TYPE.BUILDING,
        "power": 0,
        "gold": 3,
        "unit": 'inn',
        "colors": [COLOR.GRAY],
        "count": 2,
    }, {
        "name": "Taverna",
        "type": TYPE.BUILDING,
        "power": 0,
        "gold": 3,
        "unit": 'tavern',
        "colors": [COLOR.GRAY],
        "count": 1,
    }, {
        "name": "Torre",
        "type": TYPE.BUILDING,
        "power": 0,
        "gold": 3,
        "unit": 'tower',
        "colors": [COLOR.GRAY],
        "count": 1,
    }]
}
